### PR TITLE
[ALEPH-98] feat: instance logs and control

### PR DESCRIPTION
**Pull request by gmolki**
Following #97

Additionally:
- Handles confidential instances
- Supports solana chain

### CODE REVIEW

**Comment by gmolki** [comment]
Preview available at:

https://bafybeihjyqrfqzogatz3h43vlulbdd6chvkji4lkcj2fm3zbhgk6chk3tu.ipfs.aleph.sh/

**Comment by gmolki** [comment]
> not sure if it make sense to separate stdout and stderr?

I think it was splited because of some issue, @amalcaraz may have more context here

**Comment by gmolki** [comment]
> > not sure if it make sense to separate stdout and stderr?
> 
> I think it was splited because of some issue, @amalcaraz may have more context here

**Comment by olethanh** [comment]
Seems to be working fine. The logs windows could be bigger.


One suggestion for improvement, in the logs the TERMINAL color code are used. I don't know if we can add some rendering for them? Would make it look nicer. Probably can be done in a spearate PR though.

Also the loading spinner that stay displayed when there is no logs, is a bit confused we should probably have a way to indicate to the user that the connexion is successful but there is nothing to display. This will probably happen a lot with stderr. 
Not on the frontend but on some old instances  I tested the logs had rotated on the server so there was nothing displayed. I will look if I can improve the log rotation in aleph-vm

e.g.

image


see https://chrisyeh96.github.io/2020/03/28/terminal-colors.html

**Comment by olethanh** [comment]
@amalcaraz I see. I can look to add the timestamp to the message in that endpoint in the future.

**Review by olethanh — APPROVED** [review]
I cannot speak for the code I didn't look at it but I tested the deployed version and it works for me

**Comment by amalcaraz** [comment]
LGTM. Make sure to add a task on our backlog to address the two suggestion from @olethanh

**Comment by gmolki** [comment]
> One suggestion for improvement, in the logs the TERMINAL color code are used. I don't know if we can add some rendering for them? Would make it look nicer. Probably can be done in a spearate PR though.

Sure!

- https://aleph-im.atlassian.net/browse/ALEPH-342
- https://aleph-im.atlassian.net/browse/ALEPH-343

**Pull request merged**
